# Generated by Django 6.0.1 on 2026-01-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='service',
            name='tipo',
            field=models.CharField(choices=[('faxina_residencial', 'Faxina Residencial'), ('faxina_empresarial', 'Faxina Empresarial'), ('hotelaria', 'Apoio a Redes Hoteleiras'), ('mudanca', 'Mudança'), ('eletrodomesticos', 'Técnico de Eletrodomésticos'), ('eletricista', 'Eletricista'), ('servicos_gerais', 'Serviços Gerais')], default='servicos_gerais', max_length=50),
        ),
    ]
