# Generated by Django 6.0.1 on 2026-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_address_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='banheiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metragem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_faxina',
            field=models.CharField(blank=True, choices=[('padrao', 'Faxina Padrão'), ('diaria_completa', 'Diária Completa')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_imovel',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('apartamento', 'Apartamento')], max_length=20, null=True),
        ),
    ]
