# Generated by Django 6.0.1 on 2026-03-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_banheiros_order_cep_order_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bairro',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='cidade',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
