# Generated by Django 6.0.1 on 2026-03-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_bairro_order_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='materiais_limpeza',
            field=models.CharField(blank=True, max_length=502, null=True),
        ),
    ]
