# Generated by Django 6.0.1 on 2026-03-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_materiais_limpeza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='prestadores/')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('servico', models.CharField(choices=[('faxina_residencial', 'Faxina Residencial'), ('faxina_empresarial', 'Faxina Empresarial'), ('hotelaria', 'Apoio a Redes Hoteleiras'), ('mudanca', 'Mudança'), ('eletrodomesticos', 'Técnico de Eletrodomésticos'), ('eletricista', 'Eletricista'), ('servicos_gerais', 'Serviços Gerais')], max_length=50)),
                ('eletrodomesticos', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('anos_experiencia', models.PositiveIntegerField()),
                ('aceita_contato', models.BooleanField(default=False)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
