# Generated by Django 6.0.1 on 2026-03-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prestador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='servico',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
