# Generated by Django 6.0.1 on 2026-03-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_prestador_cidade_alter_prestador_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='prestadores/comprovantes/'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='doc_frente',
            field=models.ImageField(blank=True, null=True, upload_to='prestadores/docs/'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='doc_verso',
            field=models.ImageField(blank=True, null=True, upload_to='prestadores/docs/'),
        ),
    ]
