# Generated by Django 6.0.1 on 2026-03-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prestador_comprovante_prestador_doc_frente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('033', 'Santander'), ('077', 'Inter'), ('104', 'Caixa Econômica Federal'), ('237', 'Bradesco'), ('260', 'Nubank'), ('341', 'Itaú'), ('422', 'Safra'), ('756', 'Sicoob'), ('748', 'Sicredi'), ('336', 'C6 Bank'), ('380', 'PicPay'), ('290', 'PagBank'), ('323', 'Mercado Pago'), ('outro', 'Outro')], max_length=10, null=True)),
                ('agencia', models.CharField(blank=True, max_length=10, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_conta', models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança')], max_length=10, null=True)),
                ('tipo_pix', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('aleatoria', 'Chave Aleatória')], max_length=10, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=150, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='core.prestador')),
            ],
        ),
    ]
