# Generated by Django 6.0.1 on 2026-04-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEncerramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_encerramento', to='core.order')),
            ],
        ),
    ]
